a=input("Enter a number: ")
b=input("Enter a number: ")
integer=int(a)
integer1=int(b)
print(f"DataType of the value is {type(integer)} and the value is {integer}")
print(f"DataType of the value is {type(integer1)} and the value is {integer1}")
string=str(a)
string1=str(b)
print(f"DataType of the value is {type(string)} and the value is {string}")
print(f"DataType of the value is {type(string1)} and the value is {string1}")
floats=float(a)
floats1=float(b)
print(f"DataType of the value is {type(floats)} and the value is {floats}")
print(f"DataType of the value is {type(floats1)} and the value is {floats1}")

