import turtle
from random import randint
turtle.speed(1)
turtle.pensize(2)
turtle.pencolor("blue")
turtle.fillcolor("red")
turtle.begin_fill()
for i in range(4):
    turtle.forward(100)
    turtle.right(90)
turtle.end_fill()
turtle.penup()
turtle.goto(200, 0)
turtle.pendown()
turtle.fillcolor("green")
turtle.begin_fill()
for i in range(3):
    turtle.forward(100)
    turtle.right(120)
turtle.end_fill()
turtle.penup()
turtle.goto(-200, 0)
turtle.pendown()
turtle.fillcolor("yellow")
turtle.begin_fill()
for i in range(5):
    turtle.forward(100)
    turtle.right(144)
turtle.end_fill()
turtle.penup()          
turtle.goto(0, 200)
turtle.pendown()
turtle.fillcolor("purple")
turtle.begin_fill()
for i in range(6):
    turtle.forward(100)
    turtle.right(60)    
turtle.end_fill()
turtle.penup()
turtle.goto(0, -200)
turtle.pendown()
turtle.fillcolor("orange")
turtle.begin_fill()
for i in range(8):
    turtle.forward(100)
    turtle.right(45)
turtle.end_fill()